### ISSUE TITLE
Quaternion array handling

### ISSUE THREAD

**Issue by misofey** [ami-iit/liecasadi#11]
Is there a way for the SO3 class to be applied to not just one quaternion but to a whole array of them and be able to use all the functions like multiplication column-wise?

**Comment by DanielePucci** [comment]
CC @Giulero

**Comment by Giulero** [comment]
Sorry @misofey for the late reply! :)
Actually, I never thought about this use case. For now it shouldn't be possible. I guess that a possible workaround could be to wrap the SO3 objects in a list and iterate on it. 
Could you provide an example?
